import type { SurrealColumnType } from './schema/column/types.js';
import type { TableDefinition, ColumnBuilder } from './table.js';
/**
 * Maps SurrealDB column types to TypeScript types
 */
export type SurrealTypeToTS<T extends SurrealColumnType> = T extends 'string' | 'uuid' | 'record' | 'duration' | 'regex' | 'range' | 'table' | 'file' | 'literal' ? string : T extends 'int' | 'float' | 'decimal' | 'number' ? number : T extends 'bool' ? boolean : T extends 'datetime' ? Date | string : T extends 'array' | 'set' ? unknown[] : T extends 'object' ? Record<string, unknown> : T extends 'tuple' ? unknown[] : T extends 'geometry' | 'point' ? {
    type: string;
    coordinates: number[];
} : T extends 'bytes' ? Uint8Array : T extends 'function' ? (...args: unknown[]) => unknown : T extends 'any' | 'null' ? unknown : unknown;
/**
 * Extract the column type parameter from a ColumnBuilder
 */
type BuilderType<T> = T extends ColumnBuilder<infer TType> ? TType : never;
/**
 * Infer the select result type from a table definition.
 *
 * Maps each column to its TypeScript type.
 * Always includes `id: string` (SurrealDB auto-creates this).
 *
 * Uses the `_columns` property from defineTable() return type
 * for literal column name preservation.
 */
export type InferSelectResult<T extends TableDefinition> = T extends {
    _columns: Record<string, ColumnBuilder>;
} ? {
    id: string;
} & {
    [K in keyof T['_columns']]: SurrealTypeToTS<BuilderType<T['_columns'][K]>>;
} : {
    id: string;
};
/**
 * Infer the insert data type from a table definition.
 * Excludes `id` (auto-generated by SurrealDB).
 */
export type InferInsertData<T extends TableDefinition> = T extends {
    _columns: Record<string, ColumnBuilder>;
} ? {
    [K in keyof T['_columns'] as K extends 'id' ? never : K]: SurrealTypeToTS<BuilderType<T['_columns'][K]>>;
} : {};
/**
 * Infer the update data type — all fields optional, id excluded.
 */
export type InferUpdateData<T extends TableDefinition> = T extends {
    _columns: Record<string, ColumnBuilder>;
} ? Partial<{
    [K in keyof T['_columns'] as K extends 'id' ? never : K]: SurrealTypeToTS<BuilderType<T['_columns'][K]>>;
}> : Partial<{}>;
export {};
//# sourceMappingURL=infer-types.d.ts.map