project_name: 'DaliORM'
default_status: 'To Do'
statuses: ['To Do', 'In Progress', 'Done']
labels: []
date_format: dd/mm/yyyy
max_column_width: 20
default_editor: 'nvim'
auto_open_browser: false
default_port: 6422
remote_operations: true
auto_commit: false
zero_padded_ids: 3
bypass_git_hooks: false
check_active_branches: false
active_branch_days: 30
task_prefix: 'task'
gitbutler: true
